### ISSUE TITLE
With large datasets can't validate

### ISSUE THREAD

**Issue by gordonwatts** [gordonwatts/CalRatioTrainer#9]
This happens:

```text
Traceback (most recent call last):
  File "/home/gwatts/.local/bin/cr_trainer", line 8, in <module>
    sys.exit(main())
  File "/home/gwatts/calratio2019/CalRatioTrainer/cal_ratio_trainer/trainer.py", line 76, in main
    args.func(args)
  File "/home/gwatts/calratio2019/CalRatioTrainer/cal_ratio_trainer/trainer.py", line 20, in do_train
    training_runner_util(c)
  File "/home/gwatts/calratio2019/CalRatioTrainer/cal_ratio_trainer/training/runner_utils.py", line 30, in training_runner_util
    roc_scores, dir_name = train_llp(
  File "/home/gwatts/calratio2019/CalRatioTrainer/cal_ratio_trainer/training/deepJet_train_keras.py", line 181, in train_llp
    roc_auc = build_train_evaluate_model(
  File "/home/gwatts/calratio2019/CalRatioTrainer/cal_ratio_trainer/training/deepJet_train_keras.py", line 807, in build_train_evaluate_model
    original_val_hist = original_model.test_on_batch(
  File "/usr/local/lib/python3.8/dist-packages/keras/src/engine/training.py", line 2741, in test_on_batch
    iterator = data_adapter.single_batch_iterator(
  File "/usr/local/lib/python3.8/dist-packages/keras/src/engine/data_adapter.py", line 1930, in single_batch_iterator
    _check_data_cardinality(data)
  File "/usr/local/lib/python3.8/dist-packages/keras/src/engine/data_adapter.py", line 1950, in _check_data_cardinality
    raise ValueError(msg)
ValueError: Data cardinality is ambiguous:
  x sizes: 238, 238, 238, 238, 238, 238, 238, 238
  y sizes: 238, 238
  sample_weight sizes: 238, 52
```

**Comment by gordonwatts** [comment]
sample_weight sizes looks the most suspicious - it should be the same size I would have said! But I'm also not 100% sure what is the error is. Perhaps we can find the error? This is from keras:

```python
def _check_data_cardinality(data):
    num_samples = set(int(i.shape[0]) for i in tf.nest.flatten(data))
    if len(num_samples) > 1:
        msg = "Data cardinality is ambiguous:\n"
        for label, single_data in zip(["x", "y", "sample_weight"], data):
            msg += "  {} sizes: {}\n".format(
                label,
                ", ".join(
                    str(i.shape[0]) for i in tf.nest.flatten(single_data)
                ),
            )
        msg += "Make sure all arrays contain the same number of samples."
        raise ValueError(msg)
```

So from this is looks like the mc weight is the problem here. Odd!

**Comment by gordonwatts** [comment]
Second PR fixed it!
